<?php

namespace App\Providers;

use App\View\Composers\AppComposer;
use Illuminate\Support\ServiceProvider;

class ViewServiceProvider extends ServiceProvider
{
    public function register()
    {
//        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot()
    {
//        \Illuminate\Support\Facades\View::composer(['welcome','admin.posts.index',/*'*'*/], function ($view){
//            $view->with('version', 2);
//        });
        \Illuminate\Support\Facades\View::composer(['welcome','admin.posts.index',/*'*'*/], AppComposer::class);
    }
}

